### ISSUE TITLE
[BUG]👾It looks like a charset error

### ISSUE THREAD

**Issue by steve02081504** [nikolat/ukadonyu#3]
```log
"14:04:27","Taromati2","Ghost:OnSurfaceRestore","\w9\w9\w9\0\s[0]\1\s[10]"
"14:07:02","Taromati2","Ghost:OnInstallBegin","\0\s[20]嗯…"
"14:07:03","Taromati2","Ghost(Plugin,NoTranslate):OnGhostBoot","\C\![notifyplugin,うかどんゅう,OnMenuExec]\e"
"14:07:03","Taromati2","Ghost:OnInstallComplete","\![raiseplugin,Discord Rich Presence,OnDiscordPluginCustomDetail,""搞了些新东西""]\0\s[0]套件『うかどんゅう』\n\n[half]追加完成\n"
"14:07:32","Taromati2","Ghost(Plugin,NoTranslate):OnMenuExec","\![set,balloontimeout,0]\0\b[2]\_q■booting...\_q\e"
"14:07:32","Taromati2","SSTP(Local,Auth,NoTranslate)","\![raiseplugin,､ｦ､ｫ､ﾉ､螟ｦ,showSettingMenu]\e"
"14:07:42","Taromati2","Ghost(Plugin,NoTranslate):OnMenuExec","\![set,balloontimeout,0]\0\b[2]\_q■booting...\_q\e"
"14:07:42","Taromati2","SSTP(Local,Auth,NoTranslate)","\![raiseplugin,､ｦ､ｫ､ﾉ､螟ｦ,showSettingMenu]\e"
"14:07:50","Taromati2","Ghost(Plugin,NoTranslate):OnMenuExec","\![set,balloontimeout,0]\0\b[2]\_q■booting...\_q\e"
"14:07:50","Taromati2","SSTP(Local,Auth,NoTranslate)","\![raiseplugin,､ｦ､ｫ､ﾉ､螟ｦ,showSettingMenu]\e"
"14:08:21","Taromati2","Ghost:OnSurfaceRestore","\w9\w9\w9\0\s[0]\1\s[10]"
```
![图片](https://user-images.githubusercontent.com/31927825/155831968-f09030fa-855e-4489-8b91-1303816904a5.png)
Or is there something wrong with the way I'm using it?🧐

**Comment by nikolat** [comment]
I couldn't reproduce it in my environment.
Does it depend on the configuration of the SSP?
![ss](https://user-images.githubusercontent.com/496156/155848016-a3d993c9-f099-4156-8af7-2ad0e39bb86b.png)

**Comment by steve02081504** [comment]
Anyway, if you try a fix for it, you can let me know here and I'll be happy to test it with my computer
Like using a new branch for easy pulling, and then merging it into the main branch after this issue is really fixed

**Comment by nikolat** [comment]
- This plugin requires asynchronous processing.
- DirectSSTP is required for asynchronous notification of processing results.
- AKARI's DirectSSTP sending function is buggy.
  - So I use SAORI "HandUtil.dll" to send DirectSSTP.
- AKARI's SAORI call function can only use Shift_JIS.
  - I'd really like to use UTF-8.
- Hmm...

**Comment by steve02081504** [comment]
Is AKARI or HandUtil open source?
Maybe I can fix it.

**Comment by steve02081504** [comment]
> ![a](https://user-images.githubusercontent.com/31927825/155849705-00b83c09-a694-4387-bde9-fc11cf14fef3.gif)
> hemmmmmmmm

And do you have any clue about this problem?
It seems that only this button has this bug. Maybe you can reproduce it on your computer by start tromati2 and open the plug-in menu to reproduce this.

**Comment by steve02081504** [comment]
(Trying to figure out what's going on)
[ssp_shiori_log.txt](https://github.com/nikolat/ukadonyu/files/8147890/ssp_shiori_log.txt)

**Comment by steve02081504** [comment]
> * This plugin requires asynchronous processing.
> 
>     * DirectSSTP is required for asynchronous notification of processing results.
> 
>     * AKARI's DirectSSTP sending function is buggy.
>       
>       * So I use SAORI "HandUtil.dll" to send DirectSSTP.
> 
>     * AKARI's SAORI call function can only use Shift_JIS.
>       
>       * I'd really like to use UTF-8.
> 
>     * Hmm...

I think I'll write a smarter sstp sending saori sometime
As well, this inexplicable problem I reported on ssp bts, because I couldn't find the exact problem
http://ssp.shillest.net/bts/view.php?id=441

**Comment by nikolat** [comment]
> > ![a](https://user-images.githubusercontent.com/31927825/155849705-00b83c09-a694-4387-bde9-fc11cf14fef3.gif)
> > hemmmmmmmm
> 
> And do you have any clue about this problem? It seems that only this button has this bug. Maybe you can reproduce it on your computer by start tromati2 and open the plug-in menu to reproduce this.

I could reproduce this in my environment.
It seems that the OnChoiceSelectEx event went to GHOST because it was returning 204 No Content when the access token was empty.

**Comment by steve02081504** [comment]
![图片](https://user-images.githubusercontent.com/31927825/155877158-2b85d3ce-e7cc-477b-82ea-b77b255a8874.png)
I followed your method and it worked, but strangely my token is not empty.
but I still can't send a message now because it goes to the settings page

**Comment by nikolat** [comment]
I got it!
Please access the following URL.
The "display_name" field is empty, isn't it?

`https://ukadon.shillest.net/api/v1/accounts/verify_credentials?access_token= (your access token)`

**Comment by steve02081504** [comment]
![图片](https://user-images.githubusercontent.com/31927825/155877584-4fd51c1b-90ba-422b-a4e2-eb184e0b4dc3.png)
yeeeeeeeeep

**Comment by nikolat** [comment]
OK, I'll fix it soon.

**Comment by steve02081504** [comment]
fixed!
thanks for all these

**Comment by steve02081504** [comment]
Oh and don't forget the marge branch to apply the fix
#4
