### ISSUE TITLE
Interface drawing errors

### ISSUE THREAD

**Issue by steve02081504** [nikolat/ukadonyu#7]
I'm not sure when this started happening, I launched the interface on a whim today and it looked like this
![图片](https://user-images.githubusercontent.com/31927825/182799931-ba79f9a9-0d51-4934-8c10-c16e6c9b80f6.png)
I think there may be a problem with the width-related logic of the home page drawing

**Comment by steve02081504** [comment]
Incidentally, I thought it might be possible to avoid ssp lag by attaching a separate exe to pull the information & download files
Or use the httpget that comes with the sakura script, which should have the same effect

**Comment by nikolat** [comment]
Even if balloon width acquisition fails, the wrong display is no longer cached.

**Comment by nikolat** [comment]
Even if the separate exe were to be used in a separate thread to download files, the results must be notified via DirectSSTP and cannot be received by the plugin.
Even if you run it in the sakura script, it would interrupt a lot of operations of the ghost, which is not smart.
